import os

def print_github_context():
    context_vars = [
        "GITHUB_WORKFLOW", "GITHUB_RUN_ID", "GITHUB_RUN_NUMBER", "GITHUB_JOB",
        "GITHUB_ACTION", "GITHUB_ACTION_PATH", "GITHUB_ACTOR", "GITHUB_REPOSITORY",
        "GITHUB_EVENT_NAME", "GITHUB_EVENT_PATH", "GITHUB_WORKSPACE", "GITHUB_SHA",
        "GITHUB_REF", "GITHUB_HEAD_REF", "GITHUB_BASE_REF", "GITHUB_SERVER_URL",
        "GITHUB_API_URL", "GITHUB_GRAPHQL_URL", "GITHUB_REF_NAME", "GITHUB_REF_PROTECTED",
        "GITHUB_REF_TYPE", "GITHUB_REPOSITORY_OWNER", "GITHUB_RUN_ATTEMPT", "GITHUB_ENV",
        "GITHUB_PATH", "GITHUB_ACTION_REPOSITORY", "GITHUB_ACTION_REF", "GITHUB_ACTIONS",
        "GITHUB_TOKEN", "GITHUB_ACTOR_ID", "GITHUB_REPOSITORY_ID", "GITHUB_REPOSITORY_OWNER_ID",
        "GITHUB_WORKFLOW_REF", "GITHUB_WORKFLOW_SHA", "GITHUB_WORKFLOW_NAME", "GITHUB_WORKFLOW_RUN_ID",
        "GITHUB_WORKFLOW_RUN_ATTEMPT", "GITHUB_WORKFLOW_RUN_NUMBER"
    ]

    for var in context_vars:
        print(f"{var}: {os.getenv(var)}")

if __name__ == "__main__":
    print_github_context()