name: Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: ref
        run: |
          echo ${{ github.ref }}
          echo ${{ github.action }}
          echo ${{ github.action_path }}
          echo ${{ github.action_ref }}
          echo ${{ github.action_status }}
          echo ${{ github.run_number }}
          echo ${{ github.run_id }}
