name: Test

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: ref
        run: |
          echo ${{ github.ref }}
          echo ${{ github.action }}
          echo ${{ github.action_path }}
          echo ${{ github.action_ref }}
          echo ${{ github.action_status }}
          echo ${{ github.run_number }}
          echo "${{ github.run_id }}"
          echo "${{ github.run_attempt }}"
          echo "${{ github.event.head_commit.message }}"
          echo "${{ github.event_name }}"
          echo "${{ github.sha }}"
          echo "${{ github.triggering_actor }}"
          echo "${{ toJson(github) }}"

      # - name: Checkout
      #   uses: actions/checkout@v4

      # - name: Setup Terraform
      #   uses: hashicorp/setup-terraform@v1
      #   with:
      #     terraform_version: "1.6.5"

      # - name: Terraform Commands
      #   run: |
      #     terraform init
      #     terraform plan -var "github_event=${{ toJson(github.event) }}"
        # env:
        #   TF_VAR_github_event="${{ github.event.head_commit.message }}"
