name: Validate PR Title

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  pr-title-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Enforce Jira Issue Key in Pull Request Title
        uses: ryanvade/enforce-pr-title-style-action@v2.1.2
        with:
          projectKey: 'RT'
